# This workflow is the main workflow on pushing to the main branch
# and runs builds, releases, conventional commits, and pushes.

name: Main

on:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code with commit history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: liatrio/github-action-conventional-release@v1.0.0
        id: tag
        with:
          debug: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
